// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AvatarDropdown: typeof import('./src/components/GlobalHeader/AvatarDropdown.vue')['default']
    Container: typeof import('./src/components/Chart/Container.vue')['default']
    Index: typeof import('./src/components/SAlert/Index.vue')['default']
    Inex: typeof import('./src/components/Upload/inex.vue')['default']
    MessageTable: typeof import('./src/components/GlobalHeader/MessageTable.vue')['default']
    RightContent: typeof import('./src/components/GlobalHeader/RightContent.vue')['default']
  }
}

export { }
