// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    Index: typeof import('./src/components/SAlert/Index.vue')['default']
    Inex: typeof import('./src/components/Upload/inex.vue')['default']
  }
}

export {}
