FROM ubuntu:18.04

USER root
ENV DEBIAN_FRONTEND noninteractive
#COPY ./sources.list /etc/apt/sources.list
RUN sed -i 's/http:\/\/archive\.ubuntu\.com\/ubuntu\//http:\/\/mirrors\.163\.com\/ubuntu\//g' /etc/apt/sources.list

RUN apt-get update && apt-get install -yqq nginx && apt-get install -y curl wget && apt-get install -y git

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get update && apt-get install -y nodejs
# 复制项目代码
WORKDIR /src

COPY package.json /src/

RUN npm config set registry "https://registry.npm.taobao.org/" \
  && npm install

COPY . /src

COPY nginx.conf /etc/nginx/nginx.conf

RUN npm run build

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
